const { chromium } = require('playwright');
(async () => {
  const b = await chromium.launch();
  const p = await b.newPage({ viewport: { width: 1440, height: 900 } });
  p.on('pageerror', e => console.log('PAGEERROR:', e.message));
  await p.goto('http://127.0.0.1:8000', { waitUntil: 'load' });
  await p.evaluate(() => localStorage.clear());
  await p.reload({ waitUntil: 'load' });
  await p.waitForTimeout(500);
  await p.screenshot({ path: 'shots/11-star-landing.png' });
  await p.click('[data-act="open-app"]');
  await p.waitForTimeout(400);
  await p.screenshot({ path: 'shots/12-star-claim.png' });
  await p.click('[data-act="ob-claim"]');
  await p.fill('#obname', 'Nova');
  await p.click('[data-act="ob-next"]'); await p.click('[data-act="ob-next"]'); await p.click('[data-act="ob-done"]');
  await p.waitForSelector('#cprompt');
  await p.fill('#cprompt', 'Research which Swedish party people say they vote for on social media');
  await p.keyboard.press('Enter');
  await p.waitForSelector('.qopt', { timeout: 40000 });
  await p.waitForTimeout(300);
  await p.screenshot({ path: 'shots/13-newcards.png' });
  await p.click('.qopt');
  await p.waitForSelector('.prev .minibars', { timeout: 40000 });
  await p.waitForTimeout(600);
  await p.screenshot({ path: 'shots/14-artifact-prev.png' });
  // github flow for approval card
  await p.click('[data-act="newchat"]');
  await p.waitForSelector('#cprompt');
  await p.fill('#cprompt', 'Review my GitHub pull requests');
  await p.keyboard.press('Enter');
  await p.waitForSelector('[data-act="connect"]', { timeout: 30000 });
  await p.click('[data-act="connect"]');
  await p.waitForSelector('[data-act="save-secret"]', { timeout: 20000 });
  await p.fill('[data-f="val"]', 'ghp_demo123');
  await p.click('[data-act="save-secret"]');
  await p.waitForSelector('[data-act="approve"]', { timeout: 20000 });
  await p.waitForTimeout(300);
  await p.screenshot({ path: 'shots/15-approval.png' });
  // vault tabs
  await p.click('[data-act="approve"]');
  await p.click('[data-act="nav"][data-view="vault"]');
  await p.waitForSelector('.seg');
  await p.screenshot({ path: 'shots/16-vault-tabs.png' });
  await p.click('[data-act="vtab"][data-t="library"]');
  await p.waitForTimeout(300);
  await p.screenshot({ path: 'shots/17-vault-library.png' });
  console.log('shots3 done');
  await b.close();
})().catch(e => { console.error('FATAL', e.message); process.exit(1); });
