const assert=require('node:assert/strict'),fs=require('node:fs');
const {PGlite}=require('@electric-sql/pglite');
(async()=>{
  const db=new PGlite();
  await db.exec("create role anon;create role authenticated;create role service_role;create table profiles(id text primary key);insert into profiles values('owner'),('other');create schema storage;create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint);");
  await db.exec(fs.readFileSync('supabase/migrations/20260923180000_goals_and_library.sql','utf8'));
  await db.exec("insert into library_items(id,user_id,title,kind,content) values('f','owner','Old.md','document','old version');");
  await db.exec(fs.readFileSync('supabase/migrations/20260930121726_task_files_goals_permissions.sql','utf8'));
  await db.exec(fs.readFileSync('supabase/migrations/20260930121730_file_cleanup_goal_activity.sql','utf8'));
  const q=async(sql,p=[])=>(await db.query(sql,p)).rows;
  assert.equal((await q('select content from library_item_versions'))[0].content,'old version','migration preserves existing files');
  await q("update library_items set content='new version',revision=2 where id='f' and user_id='owner' and revision=1");
  assert.equal((await q('select * from library_item_versions')).length,2);
  assert.equal((await q("update library_items set content='stale edit',revision=2 where id='f' and revision=1 returning id")).length,0);
  assert.equal((await q("select content from library_items where id='f'"))[0].content,'new version');
  await db.exec("set role authenticated");
  for(const table of ['library_items','library_item_versions','agent_permission_grants','goals'])await assert.rejects(q('select * from '+table),/permission denied/);
  await db.exec('reset role');
  assert.equal((await q("select public from storage.buckets where id='library-private'"))[0].public,false);
  await q("update library_items set storage_path='owner/f/3',revision=3 where id='f'");
  await q("delete from library_items where id='f'");assert.equal((await q('select * from library_item_versions')).length,0);
  assert.equal((await q('select storage_path from library_storage_gc'))[0].storage_path,'owner/f/3','cascade deletion queues private blobs for retryable cleanup');
  await db.exec("create table sub_agents(id text primary key,user_id text,trigger_config jsonb);create table automation_runs(id text primary key,user_id text,sub_agent_id text,status text);");
  await db.exec(fs.readFileSync('supabase/migrations/20260930121729_goal_run_budget.sql','utf8'));
  await q("insert into goals(id,user_id,title,work) values('g','owner','Goal',$1)",[{enabled:true,agentId:'a',maxRuns:2}]);
  await q("insert into sub_agents values('a','owner',$1)",[{goalId:'g'}]);
  const start=id=>q("insert into automation_runs values($1,'owner','a','running')",[id]);
  await start('r1');await assert.rejects(start('overlap'),/already active/);
  await q("update automation_runs set status='done' where id='r1'");await start('r2');
  await q("update automation_runs set status='done' where id='r2'");await assert.rejects(start('r3'),/budget reached/);
  await q("update goals set status='paused' where id='g'");await assert.rejects(start('paused'),/not enabled/);
  await q("update goals set status='active',work=$1 where id='g'",[{enabled:true,configurationId:'new',nextAction:'owner action'}]);
  const activity=(run,config,next,user='owner')=>q('select record_goal_activity($1,$2,$3,$4,$5,$6)',[user,'g',{runId:run,status:'done'},config,next,null]);
  await activity('old-run','old','stale action');
  assert.equal((await q("select work from goals where id='g'"))[0].work.nextAction,'owner action');
  await activity('new-run','new','verified next action');await activity('new-run','new','duplicate');await activity('foreign','new','foreign action','other');
  const merged=(await q("select work,activity from goals where id='g'"))[0];
  assert.equal(merged.work.nextAction,'verified next action');assert.equal(merged.activity.length,2);
  await db.close();console.log('DevDay SQL: migration/backfill, atomic revision history, stale edits, private storage and account table permissions passed.');
})().catch(e=>{console.error(e);process.exitCode=1;});
