/* Goals and Library tools for the personal agent, shared by the Node and edge
   runtimes (the edge copy is generated by scripts/sync-lingon.mjs). The agent
   writes the same account rows the Goals page and Library show, so a goal it
   creates in chat appears on the Goals page and vice versa. */
const { entry } = require('./tracing');
const store = require('../store');

// The Goals page says Relationships; the stored id stays 'family' for older goals.
const GOAL_CATEGORY_ENUM = ['health', 'relationships', 'finance', 'career', 'interests', 'productivity', 'other'];
const shownCategory = (category) => category === 'family' ? 'relationships' : category;
const STEP_LIST = { type: 'array', maxItems: 30, items: { type: 'string', maxLength: 120 } };
const STEP_REFS = { type: 'array', maxItems: 30, items: { type: 'string', maxLength: 120 }, description: 'Step ids or exact step titles.' };
const LIBRARY_FORMATS = { md: ['text/markdown', 'document'], txt: ['text/plain', 'document'], html: ['text/html', 'web'],
  csv: ['text/csv', 'document'], json: ['application/json', 'document'], svg: ['image/svg+xml', 'image'] };

// Tool results stay small: the model gets metadata, never media bytes.
const goalBrief = (goal) => ({ id: goal.id, title: goal.title, category: shownCategory(goal.category), status: goal.status,
  steps: goal.steps.map((st) => ({ id: st.id, title: st.title, done: st.done })) });
const libraryBrief = (item) => ({ id: item.id, title: item.title, kind: item.kind, mime: item.mime, size: item.size,
  source: item.source, createdAt: new Date(item.createdAt).toISOString() });
const notFound = (what) => Object.assign(new Error(`${what} not found.`), { code: 'NOT_FOUND' });

const PERSONAL_TOOLS = {
  goal_list: {
    name: 'goal_list', type: 'function', approval: false,
    description: 'List the owner goals with their steps and status.',
    run: async ({ status }, ctx) => {
      const goals = await store.listGoals(ctx.userId, { status });
      ctx.trace(entry('target', `goal_list: ${goals.length}`));
      return { goals: goals.map(goalBrief) };
    },
  },
  goal_create: {
    name: 'goal_create', type: 'function', approval: false,
    description: 'Create a goal on the owner Goals page once the owner has said what they want. Keep the title short and specific; add 3-6 small concrete steps when you can.',
    run: async ({ title, category, steps }, ctx) => {
      const goal = await store.createGoal(ctx.userId, { title, category, steps, chatId: ctx.chatId || ctx.sessionId });
      ctx.trace(entry('target', `goal_create: ${goal.title}`));
      return { ...goalBrief(goal), action: 'created' };
    },
  },
  goal_update: {
    name: 'goal_update', type: 'function', approval: false,
    description: 'Change a goal: rename it, change category, pause/resume/complete it, or add, check off, reopen or remove steps.',
    run: async ({ id, title, category, status, add_steps, complete_steps, reopen_steps, remove_steps }, ctx) => {
      const goal = await store.updateGoal(ctx.userId, String(id || ''), { title, category, status,
        addSteps: add_steps, completeSteps: complete_steps, reopenSteps: reopen_steps, removeSteps: remove_steps });
      ctx.trace(entry('target', `goal_update: ${goal.title} (${goal.status})`));
      return { ...goalBrief(goal), action: 'updated' };
    },
  },
  goal_delete: {
    name: 'goal_delete', type: 'function', approval: false,
    description: 'Delete a goal by id, only when the owner asks for it to be removed.',
    run: async ({ id }, ctx) => {
      const goal = await store.getGoal(ctx.userId, String(id || ''));
      if (!goal) throw notFound('Goal');
      await store.deleteGoal(ctx.userId, goal.id);
      ctx.trace(entry('target', `goal_delete: ${goal.title}`));
      return { id: goal.id, title: goal.title, action: 'deleted' };
    },
  },
  library_list: {
    name: 'library_list', type: 'function', approval: false,
    description: 'List files in the owner Library (documents, web pages, images, video, audio) with ids, names and sizes.',
    run: async ({ kind, query, limit }, ctx) => {
      const items = await store.listLibrary(ctx.userId, { kind, query, limit: Math.min(Number(limit) || 30, 100) });
      ctx.trace(entry('library', `library_list: ${items.length}`));
      return { items: items.map(libraryBrief) };
    },
  },
  library_read: {
    name: 'library_read', type: 'function', approval: false,
    description: 'Read one Library item by id. Text files return their content; media returns details only.',
    run: async ({ id }, ctx) => {
      const item = await store.getLibraryItem(ctx.userId, String(id || ''));
      if (!item) throw notFound('Library item');
      ctx.trace(entry('library', `library_read: ${item.title}`));
      const media = item.content.startsWith('data:');
      return { ...libraryBrief(item), content: media ? undefined : item.content.slice(0, 60000), truncated: !media && item.content.length > 60000 };
    },
  },
  library_save: {
    name: 'library_save', type: 'function', approval: false,
    description: 'Save a text artifact (Markdown, text, HTML, CSV, JSON or SVG) to the owner Library as a file they can keep.',
    run: async ({ title, format, content }, ctx) => {
      const [mime, kind] = LIBRARY_FORMATS[format] || LIBRARY_FORMATS.md;
      const ext = Object.keys(LIBRARY_FORMATS).find((key) => LIBRARY_FORMATS[key][0] === mime);
      const name = /\.[a-z0-9]{2,5}$/i.test(String(title || '')) ? String(title) : `${String(title || 'Untitled').trim()}.${ext}`;
      const item = await store.saveLibraryItem(ctx.userId, { title: name, mime, kind, content, source: 'agent', chatId: ctx.chatId || ctx.sessionId });
      ctx.trace(entry('library', `library_save: ${item.title}`));
      return { ...libraryBrief(item), action: 'saved' };
    },
  },
  library_rename: {
    name: 'library_rename', type: 'function', approval: false,
    description: 'Rename one Library item by id.',
    run: async ({ id, title }, ctx) => {
      const item = await store.renameLibraryItem(ctx.userId, String(id || ''), title);
      ctx.trace(entry('library', `library_rename: ${item.title}`));
      return { ...libraryBrief(item), action: 'renamed' };
    },
  },
  library_delete: {
    name: 'library_delete', type: 'function', approval: true,
    description: 'Permanently delete one Library item by id. REQUIRES owner approval.',
    approvalDetail: async ({ id }, { userId }) => {
      const item = await store.getLibraryItem(userId, String(id || ''));
      return item ? `Delete “${item.title}” from your Library` : 'Delete a Library item';
    },
    run: async ({ id }, ctx) => {
      const item = await store.getLibraryItem(ctx.userId, String(id || ''));
      if (!item) throw notFound('Library item');
      await store.deleteLibraryItem(ctx.userId, item.id);
      ctx.trace(entry('library', `library_delete: ${item.title}`));
      return { id: item.id, title: item.title, action: 'deleted' };
    },
  },
};

const PERSONAL_TOOL_SCHEMAS = [
  { name: 'goal_list', description: 'List the owner goals, steps and progress. Check before creating a similar goal.', parameters: { type: 'object', properties: { status: { type: 'string', enum: ['active', 'paused', 'done'] } } } },
  { name: 'goal_create', description: 'Create a goal on the owner Goals page when they decide what they want to work towards. Short specific title, a category, and 3-6 small concrete steps.', parameters: { type: 'object', properties: { title: { type: 'string', maxLength: 120 }, category: { type: 'string', enum: GOAL_CATEGORY_ENUM }, steps: STEP_LIST }, required: ['title', 'category'] } },
  { name: 'goal_update', description: 'Update a goal by id: rename, recategorize, set status (active, paused, done), or add, complete, reopen or remove steps.', parameters: { type: 'object', properties: { id: { type: 'string' }, title: { type: 'string', maxLength: 120 }, category: { type: 'string', enum: GOAL_CATEGORY_ENUM }, status: { type: 'string', enum: ['active', 'paused', 'done'] }, add_steps: STEP_LIST, complete_steps: STEP_REFS, reopen_steps: STEP_REFS, remove_steps: STEP_REFS }, required: ['id'] } },
  { name: 'goal_delete', description: 'Delete a goal by id only when the owner asks to remove it.', parameters: { type: 'object', properties: { id: { type: 'string' } }, required: ['id'] } },
  { name: 'library_list', description: 'List the owner Library files (documents, web pages, images, video, audio). Filter by kind or name.', parameters: { type: 'object', properties: { kind: { type: 'string', enum: ['document', 'web', 'image', 'video', 'audio', 'file'] }, query: { type: 'string', maxLength: 120 }, limit: { type: 'integer', minimum: 1, maximum: 100 } } } },
  { name: 'library_read', description: 'Read one Library item by id. Returns text content for documents and pages; details only for media.', parameters: { type: 'object', properties: { id: { type: 'string' } }, required: ['id'] } },
  { name: 'library_save', description: 'Save a text artifact to the owner Library so they can keep, open and download it.', parameters: { type: 'object', properties: { title: { type: 'string', maxLength: 160 }, format: { type: 'string', enum: Object.keys(LIBRARY_FORMATS) }, content: { type: 'string', maxLength: 500000 } }, required: ['title', 'format', 'content'] } },
  { name: 'library_rename', description: 'Rename one Library item by id.', parameters: { type: 'object', properties: { id: { type: 'string' }, title: { type: 'string', maxLength: 160 } }, required: ['id', 'title'] } },
  { name: 'library_delete', description: 'Permanently delete one Library item by id. REQUIRES owner approval.', parameters: { type: 'object', properties: { id: { type: 'string' } }, required: ['id'] } },
];

// Matched against foldText output (ASCII), across the same languages as TOOL_KEYWORDS.
const PERSONAL_KEYWORDS = {
  goals: /(goal|milestone|habit|resolution|objective|progress|\bmal(et|en)?\b|delmal|\bmaal\b|\bziel|objectif|\bmeta\b|\bmetas\b|objetivo)/,
  library: /(library|artifact|artefakt|bibliotek|bibliothe|biblioteca|my (files|documents|images|photos|pictures|videos|uploads)|uploaded|saved (file|document|image|page)|rename|mina filer|mine filer|meine dateien|mes fichiers|mis archivos)/,
};
function pickPersonalTools(foldedTask) {
  const names = [];
  if (PERSONAL_KEYWORDS.goals.test(foldedTask)) names.push('goal_list', 'goal_create', 'goal_update', 'goal_delete');
  if (PERSONAL_KEYWORDS.library.test(foldedTask)) names.push('library_list', 'library_read', 'library_save', 'library_rename', 'library_delete');
  return names;
}

// Pages, Canvas files and generated images are real artifacts: keep a copy in
// the Library and tag the result so its chat card links to that Library item.
// A Library failure never fails the tool that produced the artifact.
function withLibraryAutosave(tools) {
  const capture = {
    build_page: (out) => out?.html && { title: 'your-page.html', mime: 'text/html', kind: 'web', content: out.html },
    canvas_show: (out) => {
      if (!out?.title || !out.content) return null;
      const ext = { md: 'md', html: 'html', json: 'json', csv: 'csv', svg: 'svg' }[out.format] || 'txt';
      const [mime, kind] = LIBRARY_FORMATS[ext];
      return { title: /\.[a-z0-9]{2,5}$/i.test(out.title) ? out.title : `${out.title}.${ext}`, mime, kind, content: out.content };
    },
    image_generate: (out) => out?.dataUrl && { title: out.name || 'generated.png', mime: out.mimeType || 'image/png', kind: 'image', content: out.dataUrl },
  };
  for (const [name, toItem] of Object.entries(capture)) {
    const tool = tools[name];
    if (!tool || tool.libraryAutosave) continue;
    const run = tool.run;
    tools[name] = { ...tool, libraryAutosave: true, run: async (args, ctx) => {
      const out = await run(args, ctx);
      const item = toItem(out);
      if (!item) return out;
      try {
        const saved = await store.saveLibraryItem(ctx.userId, { ...item, source: 'agent', chatId: ctx.chatId || ctx.sessionId });
        return { ...out, libraryId: saved.id };
      } catch (error) {
        ctx.trace?.(entry('library', `library autosave skipped: ${error.message}`));
        return out;
      }
    } };
  }
  return tools;
}

// Chat card for a goal or Library change, so the app refreshes that view and
// shows the owner what changed. Read-only calls produce no card.
function personalResultCard(name, out) {
  if (!out || out.error || !out.action) return null;
  if (name.startsWith('goal_')) {
    const steps = Array.isArray(out.steps) ? out.steps : [];
    return { type: 'goal', action: out.action, goalId: out.id, title: out.title, category: out.category || null,
      goalStatus: out.status || null, stepsDone: steps.filter((st) => st.done).length, stepsTotal: steps.length, status: 'done' };
  }
  if (name.startsWith('library_')) return { type: 'library', action: out.action, libraryId: out.id, title: out.title, kind: out.kind || null, status: 'done' };
  return null;
}
// Coordinator-safe subset: fast account reads/writes with no approval step.
const QUICK_PERSONAL_TOOLS = new Set(['goal_list', 'goal_create', 'goal_update', 'goal_delete', 'library_list', 'library_read', 'library_rename']);

module.exports = { PERSONAL_TOOLS, PERSONAL_TOOL_SCHEMAS, QUICK_PERSONAL_TOOLS, pickPersonalTools, withLibraryAutosave, personalResultCard };
