/* The owner's own connectors: REST APIs and remote MCP servers they add themselves.
   - The credential is a vault secret (AES-256-GCM, see store.js). A connector keeps only
     the secret's id; the value is read here for one request and never reaches the model.
     Results are scrubbed of it in case a server echoes it back.
   - Requests go from the server, not the VM: the VM's job containers have no network.
     Every address must be public https, checked again on each redirect, so a connector
     cannot reach loopback, private networks or cloud metadata.
   - MCP: Streamable HTTP, falling back to the older HTTP+SSE transport.
   - Permissions: each MCP tool, and each HTTP method of an API, can be turned off. Reads
     run when the owner asks; writes follow the connected-app approval setting.
   The edge copy in src/lingon-server/ is generated by scripts/sync-lingon.mjs. */
const store = require('./store');
const { compactParams, compactResult } = require('./composio');
const { publicUrlProblem, hostResolvesPublic, pinnedFetch } = require('./agents/sandbox');

const KINDS = new Set(['api', 'mcp']);
const AUTH_TYPES = new Set(['none', 'bearer', 'header', 'query', 'basic']);
const API_METHODS = [
  { slug: 'GET', name: 'Read data', description: 'GET requests: look things up without changing anything.', kind: 'read' },
  { slug: 'POST', name: 'Create and run', description: 'POST requests: create records, send messages or run actions.', kind: 'write' },
  { slug: 'PUT', name: 'Replace', description: 'PUT requests: replace existing records.', kind: 'write' },
  { slug: 'PATCH', name: 'Update', description: 'PATCH requests: change existing records.', kind: 'write' },
  { slug: 'DELETE', name: 'Delete', description: 'DELETE requests: remove records.', kind: 'write' },
];
const MCP_PROTOCOL = '2025-06-18';
const CLIENT_INFO = { name: 'Belna', version: '1.0' };
const MAX_TOOLS = 100;
const MAX_BODY_BYTES = 1024 * 1024;
const REDIRECTS = new Set([301, 302, 303, 307, 308]);
// Headers the agent may not set on an API request; credentials come only from the vault.
const RESERVED_HEADERS = /^(?:authorization|proxy-authorization|cookie|host|content-length|connection|transfer-encoding|te|upgrade|x-forwarded-.*|forwarded|mcp-session-id|mcp-protocol-version)$/i;
const READ_WORDS = /(?:^|_)(?:LIST|GET|FETCH|SEARCH|READ|QUERY|FIND|LOOKUP|SHOW|DESCRIBE|COUNT|CHECK|STATUS|VIEW|EXPORT|DOWNLOAD|ASK|EXPLAIN|SUMMARI[SZ]E|INSPECT|PREVIEW)(?:_|$)/;
const WRITE_WORDS = /(?:^|_)(?:SEND|CREATE|ADD|UPDATE|DELETE|POST|WRITE|INSERT|REMOVE|TRASH|ARCHIVE|MODIFY|REPLY|FORWARD|UPLOAD|PUBLISH|INVITE|EDIT|PATCH|PUT|MOVE|RENAME|SHARE|MERGE|APPROVE|CANCEL|SCHEDULE|BOOK|PAY|CHARGE|TRANSFER|SET|RUN|EXECUTE|TRIGGER|START|STOP|CLOSE|OPEN|ASSIGN|COMMENT|SUBMIT|DEPLOY|RESTART|ENABLE|DISABLE|CLEAR|RESET|REVOKE|GRANT|IMPORT|SYNC|MARK|LABEL|TAG)(?:_|$)/;

const badInput = (message) => Object.assign(new Error(message), { code: 'BAD_INPUT' });
const clean = (value, max) => String(value ?? '').replace(/\s+/g, ' ').trim().slice(0, max);
const humanize = (name) => {
  const text = String(name || '').replace(/([a-z0-9])([A-Z])/g, '$1 $2').replace(/[_.-]+/g, ' ').trim().toLowerCase();
  return text ? text[0].toUpperCase() + text.slice(1) : '';
};
const hostOf = (url) => { try { return new URL(url).hostname; } catch { return ''; } };

// ---- input ----
function cleanUrl(value, label = 'URL') {
  let u;
  try { u = new URL(String(value || '').trim()); } catch { throw badInput(`Enter the full ${label}, starting with https://`); }
  if (u.protocol !== 'https:') throw badInput(`The ${label} must start with https://`);
  const problem = publicUrlProblem(u.href);
  if (problem) throw badInput(`That ${label} is not a public internet address (${problem}).`);
  u.hash = '';
  if (u.href.length > 1000) throw badInput(`That ${label} is too long.`);
  return u.href;
}
function cleanAuth(auth = {}) {
  const type = AUTH_TYPES.has(auth.type) ? auth.type : 'none';
  const out = { type };
  if (type === 'header') {
    const header = String(auth.header || '').trim();
    if (!/^[A-Za-z0-9][A-Za-z0-9-]{0,59}$/.test(header) || (RESERVED_HEADERS.test(header) && !/^authorization$/i.test(header))) throw badInput('Enter the header name the service expects, such as X-API-Key.');
    out.header = header;
  }
  if (type === 'query') {
    const param = String(auth.param || '').trim();
    if (!/^[A-Za-z0-9_.-]{1,60}$/.test(param)) throw badInput('Enter the query parameter name, such as api_key.');
    out.param = param;
  }
  if (type === 'basic') {
    const username = String(auth.username || '').trim().slice(0, 200);
    if (username.includes(':')) throw badInput('A basic auth username cannot contain a colon.');
    if (username) out.username = username;
  }
  return out;
}
function cleanInput(input = {}) {
  const kind = String(input.kind || '').toLowerCase();
  if (!KINDS.has(kind)) throw badInput('Choose API or MCP server.');
  const name = clean(input.name, 60);
  if (!name) throw badInput('Give the connector a name.');
  const url = cleanUrl(input.url, kind === 'mcp' ? 'server URL' : 'base URL');
  const auth = cleanAuth(input.auth);
  const secret = typeof input.secret === 'string' ? input.secret.trim() : '';
  if (secret.length > 4000) throw badInput('That key is too long to store (4,000 characters max).');
  if (auth.type !== 'none' && !secret) throw badInput(kind === 'mcp' ? 'Paste the token for this server, or choose No authentication.' : 'Paste the API key, or choose No authentication.');
  const testPath = kind === 'api' ? clean(input.testPath, 300) : '';
  if (testPath && (/^[a-z][a-z0-9+.-]*:/i.test(testPath) || testPath.startsWith('//'))) throw badInput('The test path goes after the base URL, such as /v1/me.');
  return {
    kind, name, url, auth, secret: auth.type === 'none' ? '' : secret, testPath,
    description: clean(input.description, 600),
    docsUrl: input.docsUrl ? cleanUrl(input.docsUrl, 'docs link') : '',
  };
}
// The agent sets a connector up: it names the service, its address and how it signs in.
// The owner sees where the key goes, pastes it into a chat card, and the card adds the
// connector through /api/connectors. The key never passes through the agent.
function setupArgs(args = {}) {
  const kind = String(args.kind || '').toLowerCase();
  if (!KINDS.has(kind)) throw badInput('kind must be mcp or api.');
  const name = clean(args.name, 60);
  if (!name) throw badInput('name is the service, e.g. Linear.');
  const url = cleanUrl(args.url, kind === 'mcp' ? 'server URL' : 'base URL');
  const type = String(args.auth || 'bearer').toLowerCase();
  if (!AUTH_TYPES.has(type)) throw badInput('auth must be bearer, header, query, basic or none.');
  const auth = cleanAuth({ type, header: args.header, param: args.param, username: args.username });
  const testPath = kind === 'api' ? clean(args.test_path, 300) : '';
  if (testPath && (/^[a-z][a-z0-9+.-]*:/i.test(testPath) || testPath.startsWith('//'))) throw badInput('test_path goes after the base URL, such as /v1/me.');
  const link = (value, label) => { if (!value) return ''; try { return cleanUrl(value, label); } catch { return ''; } };
  return { kind, name, url, host: hostOf(url), auth, testPath, description: clean(args.description, 600),
    docsUrl: kind === 'api' ? link(args.docs_url, 'docs link') : '', keyUrl: link(args.key_url, 'key page'), reason: clean(args.reason, 240) };
}
// The site a host belongs to: its last two labels, or three under a country's second level
// such as co.uk. Close enough to tell the owner that a key and its destination differ.
function siteOf(host) {
  const labels = String(host || '').toLowerCase().split('.').filter(Boolean);
  const n = labels.length >= 3 && labels.at(-1).length === 2 && /^(?:co|com|net|org|gov|ac|edu)$/.test(labels.at(-2)) ? 3 : 2;
  return labels.slice(-n).join('.');
}
// The agent names the service and both addresses (it may have read them on a page written to
// mislead it), so the card says plainly when they do not line up: a key made on one site and
// sent to another is how a key is phished.
function setupWarning(v) {
  const keySite = siteOf(hostOf(v.keyUrl));
  if (v.auth.type === 'none' || !keySite || keySite === siteOf(v.host)) return '';
  return `You get this key on ${keySite}, but it is sent to ${v.host}. Continue only if ${v.host} belongs to ${v.name}.`;
}
function setupCard(args) {
  const v = setupArgs(args);
  return { type: 'connector', kind: v.kind, name: v.name, url: v.url, host: v.host, auth: v.auth, testPath: v.testPath, description: v.description, docsUrl: v.docsUrl, keyUrl: v.keyUrl, note: v.reason, warning: setupWarning(v) };
}
function setupDetail(args) {
  const v = setupArgs(args);
  return JSON.stringify({ summary: `Connect ${v.name}, ${v.kind === 'mcp' ? 'an MCP server' : 'an API'} at ${v.host}`, name: v.name, url: v.url, auth: v.auth.type });
}
function slugFor(name, taken) {
  const base = String(name).toLowerCase().normalize('NFD').replace(/[̀-ͯ]/g, '').replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '').slice(0, 40) || 'connector';
  let slug = base, n = 2;
  while (taken.has(slug)) slug = `${base}-${n++}`;
  return slug;
}

// ---- network ----
function timeoutSignal(ms, signal) {
  const timeout = AbortSignal.timeout(ms);
  if (!signal) return timeout;
  if (AbortSignal.any) return AbortSignal.any([signal, timeout]);
  const ctrl = new AbortController();
  for (const s of [signal, timeout]) { if (s.aborted) ctrl.abort(s.reason); else s.addEventListener('abort', () => ctrl.abort(s.reason), { once: true }); }
  return ctrl.signal;
}
async function publicTarget(url) {
  const problem = publicUrlProblem(url);
  const u = new URL(url);
  if (problem || u.protocol !== 'https:') throw Object.assign(new Error(`${u.hostname || 'That address'} is not a public https address${problem ? ` (${problem})` : ''}.`), { code: 'HOST_BLOCKED' });
  if (!(await hostResolvesPublic(u.hostname))) throw Object.assign(new Error(`${u.hostname} resolves to a private address.`), { code: 'HOST_BLOCKED' });
  return u;
}
// Requests connect only to the address that was checked (see pinnedFetch). Tests swap in
// their own fetch with useTransport.
let transport = pinnedFetch;
function useTransport(fn) { transport = fn || pinnedFetch; }
// One request with redirects checked hop by hop. A credential header never follows a
// redirect to another site; sameOrigin refuses such a redirect outright.
async function send(url, init, { signal, sameOrigin = false, authHeaders = [] } = {}) {
  let current = url, options = { ...init, headers: { ...(init.headers || {}) } };
  for (let hop = 0; hop <= 4; hop++) {
    const target = await publicTarget(current);
    const res = await transport(target.href, { ...options, redirect: 'manual', signal });
    if (!REDIRECTS.has(res.status)) return res;
    try { await res.body?.cancel(); } catch {}
    const location = res.headers.get('location');
    if (!location) throw new Error(`${target.hostname} redirected without an address.`);
    const next = new URL(location, target);
    if (next.origin !== target.origin) {
      if (sameOrigin) throw new Error(`${target.hostname} redirected to another site (${next.hostname}).`);
      for (const name of authHeaders) delete options.headers[name];
    }
    if (res.status === 303 || ((res.status === 301 || res.status === 302) && options.method === 'POST')) options = { ...options, method: 'GET', body: undefined };
    current = next.href;
  }
  throw new Error('Too many redirects.');
}
async function readText(res, maxBytes = MAX_BODY_BYTES) {
  if (!res.body) return { text: '', truncated: false };
  const reader = res.body.getReader(), decoder = new TextDecoder();
  let text = '', size = 0, truncated = false;
  try {
    for (;;) {
      const { value, done } = await reader.read();
      if (done) break;
      size += value.byteLength;
      text += decoder.decode(value, { stream: true });
      if (size >= maxBytes) { truncated = true; break; }
    }
  } finally { try { await reader.cancel(); } catch {} }
  return { text: text + decoder.decode(), truncated };
}
// Server-sent events from a fetch body, one { event, data } at a time.
async function* sseEvents(body) {
  const reader = body.getReader(), decoder = new TextDecoder();
  let buffer = '', size = 0;
  try {
    for (;;) {
      const { value, done } = await reader.read();
      if (done) return;
      size += value.byteLength;
      if (size > 8 * MAX_BODY_BYTES) throw new Error('The server sent too much data.');
      buffer += decoder.decode(value, { stream: true });
      let gap;
      while ((gap = /\r?\n\r?\n/.exec(buffer))) {
        const block = buffer.slice(0, gap.index);
        buffer = buffer.slice(gap.index + gap[0].length);
        const event = { event: 'message', data: '' }, data = [];
        for (const line of block.split(/\r?\n/)) {
          if (!line || line.startsWith(':')) continue;
          const at = line.indexOf(':');
          const field = at < 0 ? line : line.slice(0, at);
          let v = at < 0 ? '' : line.slice(at + 1);
          if (v.startsWith(' ')) v = v.slice(1);
          if (field === 'event') event.event = v;
          else if (field === 'data') data.push(v);
        }
        event.data = data.join('\n');
        yield event;
      }
    }
  } finally { try { await reader.cancel(); } catch {} }
}
// Adds the saved credential. Returns the URL (a query credential goes in it) and the
// header names that carry it.
function authorize(url, headers, auth = {}, secret = '') {
  const u = new URL(url);
  if (!secret || !auth.type || auth.type === 'none') return { url: u.href, authHeaders: [] };
  if (auth.type === 'query') { u.searchParams.set(auth.param, secret); return { url: u.href, authHeaders: [] }; }
  if (auth.type === 'bearer') headers.Authorization = `Bearer ${secret}`;
  else if (auth.type === 'basic') headers.Authorization = 'Basic ' + Buffer.from(auth.username ? `${auth.username}:${secret}` : `${secret}:`, 'utf8').toString('base64');
  else if (auth.type === 'header') headers[auth.header] = secret;
  return { url: u.href, authHeaders: [auth.type === 'header' ? auth.header : 'Authorization'] };
}
// Every form the credential takes on the way out, so a server that echoes the request back
// (its headers or URL) shows none of them: the raw value, as a URL parameter, and as the
// Basic auth pair.
function secretForms(secret, auth = {}) {
  const forms = [secret, encodeURIComponent(secret), new URLSearchParams({ k: secret }).toString().slice(2)];
  if (auth.type === 'basic') {
    const pair = Buffer.from(auth.username ? `${auth.username}:${secret}` : `${secret}:`, 'utf8').toString('base64');
    forms.push(pair, pair.replace(/=+$/, ''));
  }
  return forms;
}
function scrub(value, secret, auth) {
  if (!secret || secret.length < 4) return value;
  const needles = secretForms(secret, auth).map((form) => JSON.stringify(form).slice(1, -1)).filter((n, i, all) => n && all.indexOf(n) === i);
  let text = JSON.stringify(value ?? null);
  if (!needles.some((n) => text.includes(n))) return value;
  for (const n of needles) text = text.split(n).join('[protected]');
  try { return JSON.parse(text); } catch { return '[protected]'; }
}
// fetch's own failures say only "fetch failed".
function reachError(error, url) {
  const host = hostOf(url) || 'The server';
  if (error?.name === 'TimeoutError') return Object.assign(new Error(`${host} did not answer in time.`), { code: 'UNREACHABLE' });
  if (error instanceof TypeError && /fetch|network|connect|socket|dns/i.test(error.message)) return Object.assign(new Error(`Could not reach ${host}. Check the address.`), { code: 'UNREACHABLE' });
  return error;
}
function httpError(res, what) {
  if (res.status === 401 || res.status === 403) {
    // MCP servers that sign in through the browser (OAuth) point to their authorization metadata.
    const oauth = /resource_metadata|oauth/i.test(res.headers?.get?.('www-authenticate') || '');
    return Object.assign(new Error(`${what} refused access (HTTP ${res.status}).${oauth ? ' It may only allow signing in through the browser (OAuth), which your own connectors don’t support yet; use an API token if the service offers one.' : ' Check the key or token under Connectors.'}`), { code: 'AUTH_FAILED', status: res.status });
  }
  return Object.assign(new Error(`${what} answered HTTP ${res.status}.`), { status: res.status });
}

// ---- MCP ----
function mcpError(error) {
  return Object.assign(new Error(String(error?.message || 'The MCP server returned an error.').slice(0, 400)), { code: 'MCP_ERROR', mcpCode: error?.code });
}
async function readRpc(res, id) {
  const type = String(res.headers.get('content-type') || '');
  if (type.includes('text/event-stream')) {
    for await (const event of sseEvents(res.body)) {
      let msg;
      try { msg = JSON.parse(event.data); } catch { continue; }
      const found = (Array.isArray(msg) ? msg : [msg]).find((m) => m && m.id === id && ('result' in m || 'error' in m));
      if (found) return found;
    }
    throw new Error('The MCP server closed the stream without an answer.');
  }
  const { text } = await readText(res);
  let msg;
  try { msg = JSON.parse(text); } catch { throw new Error('The MCP server did not answer with JSON. Check the server URL.'); }
  const found = (Array.isArray(msg) ? msg : [msg]).find((m) => m && m.id === id);
  if (!found) throw new Error('The MCP server answered without a result.');
  return found;
}
// Streamable HTTP: POST each JSON-RPC message; the answer is JSON or an SSE stream.
async function openStreamable(url, headers, authHeaders, signal) {
  let nextId = 1, extra = {};
  const post = (message) => send(url, { method: 'POST', headers: { ...headers, ...extra, 'Content-Type': 'application/json', Accept: 'application/json, text/event-stream' }, body: JSON.stringify(message) }, { signal, sameOrigin: true, authHeaders });
  const init = { jsonrpc: '2.0', id: nextId++, method: 'initialize', params: { protocolVersion: MCP_PROTOCOL, capabilities: {}, clientInfo: CLIENT_INFO } };
  const res = await post(init);
  if (!res.ok) {
    try { await res.body?.cancel(); } catch {}
    return { failed: res };
  }
  const reply = await readRpc(res, init.id);
  if (reply.error) throw mcpError(reply.error);
  const sessionId = res.headers.get('mcp-session-id');
  extra = { ...(sessionId ? { 'Mcp-Session-Id': sessionId } : {}), 'MCP-Protocol-Version': String(reply.result?.protocolVersion || MCP_PROTOCOL) };
  const note = await post({ jsonrpc: '2.0', method: 'notifications/initialized' });
  try { await note.body?.cancel(); } catch {}
  return {
    transport: 'http', server: reply.result?.serverInfo || {},
    async request(method, params) {
      const message = { jsonrpc: '2.0', id: nextId++, method, params };
      const r = await post(message);
      if (!r.ok) { try { await r.body?.cancel(); } catch {} throw httpError(r, 'The MCP server'); }
      const out = await readRpc(r, message.id);
      if (out.error) throw mcpError(out.error);
      return out.result;
    },
    close() {
      if (!sessionId) return;
      send(url, { method: 'DELETE', headers: { ...headers, ...extra } }, { signal: AbortSignal.timeout(3000), sameOrigin: true, authHeaders }).then((r) => r.body?.cancel()).catch(() => {});
    },
  };
}
// The older HTTP+SSE transport: a GET stream names the endpoint to POST to, and the
// answers arrive on that stream.
async function openLegacySse(url, headers, auth, secret, authHeaders, signal) {
  const res = await send(url, { method: 'GET', headers: { ...headers, Accept: 'text/event-stream' } }, { signal, sameOrigin: true, authHeaders });
  if (!res.ok || !String(res.headers.get('content-type') || '').includes('text/event-stream')) {
    if (res.status === 401 || res.status === 403) { try { await res.body?.cancel(); } catch {} throw httpError(res, 'The MCP server'); }
    // Servers that dropped this transport often say where to go instead.
    let hint = '';
    try { const said = JSON.parse((await readText(res, 4000)).text); hint = clean(said.message || said.error_description || (typeof said.error === 'string' ? said.error : said.error?.message), 240); } catch {}
    if (hint) throw Object.assign(new Error(`The server says: ${hint}`), { code: 'CHECK_FAILED' });
    if (!res.ok) throw httpError(res, 'The MCP server');
    throw Object.assign(new Error('That address is not an MCP server. Use the server’s MCP URL, often ending in /mcp or /sse.'), { code: 'CHECK_FAILED' });
  }
  const events = sseEvents(res.body);
  const next = async () => {
    const { value, done } = await events.next();
    if (done) throw new Error('The MCP server closed the connection.');
    return value;
  };
  let endpoint = null;
  while (!endpoint) {
    const event = await next();
    if (event.event === 'endpoint') endpoint = new URL(event.data.trim(), url);
  }
  if (endpoint.origin !== new URL(url).origin) { await events.return(); throw new Error('The MCP server pointed to another site.'); }
  const target = authorize(endpoint.href, {}, auth, secret).url;
  let nextId = 1;
  const post = async (message) => {
    const r = await send(target, { method: 'POST', headers: { ...headers, 'Content-Type': 'application/json' }, body: JSON.stringify(message) }, { signal, sameOrigin: true, authHeaders });
    try { await r.body?.cancel(); } catch {}
    if (!r.ok) throw httpError(r, 'The MCP server');
  };
  const request = async (method, params) => {
    const message = { jsonrpc: '2.0', id: nextId++, method, params };
    await post(message);
    for (;;) {
      const event = await next();
      if (event.event !== 'message') continue;
      let msg;
      try { msg = JSON.parse(event.data); } catch { continue; }
      if (msg && msg.id === message.id) {
        if (msg.error) throw mcpError(msg.error);
        return msg.result;
      }
    }
  };
  try {
    const init = await request('initialize', { protocolVersion: MCP_PROTOCOL, capabilities: {}, clientInfo: CLIENT_INFO });
    await post({ jsonrpc: '2.0', method: 'notifications/initialized' });
    return { transport: 'sse', server: init?.serverInfo || {}, request, close() { events.return().catch(() => {}); } };
  } catch (error) { events.return().catch(() => {}); throw error; }
}
async function openMcp(connector, secret, signal) {
  const headers = {};
  const auth = connector.config?.auth || {};
  const { url, authHeaders } = authorize(connector.url, headers, auth, secret);
  if (connector.config?.transport !== 'sse') {
    const session = await openStreamable(url, headers, authHeaders, signal);
    if (!session.failed) return session;
    // A server that predates Streamable HTTP refuses the POST (400, 404 or 405).
    if (![400, 404, 405].includes(session.failed.status)) throw httpError(session.failed, 'The MCP server');
    try { return await openLegacySse(url, headers, auth, secret, authHeaders, signal); }
    catch (error) { if (['AUTH_FAILED', 'HOST_BLOCKED', 'CHECK_FAILED'].includes(error.code)) throw error; throw httpError(session.failed, 'The MCP server'); }
  }
  return openLegacySse(url, headers, auth, secret, authHeaders, signal);
}
function mcpToolKind(tool) {
  const hints = tool.annotations || {};
  if (hints.readOnlyHint === true) return 'read';
  if (hints.destructiveHint === true) return 'write';
  const words = String(tool.name || '').replace(/([a-z0-9])([A-Z])/g, '$1_$2').replace(/[^A-Za-z0-9]+/g, '_').toUpperCase();
  if (WRITE_WORDS.test(words)) return 'write';
  if (READ_WORDS.test(words)) return 'read';
  // Unknown tools ask first.
  return 'write';
}
function mapMcpTool(tool) {
  const name = String(tool?.name || '');
  if (!/^[A-Za-z0-9_.\-/]{1,128}$/.test(name)) return null;
  return {
    name, title: clean(tool.title || tool.annotations?.title, 120),
    description: clean(tool.description, 400), kind: mcpToolKind(tool),
    args: compactParams(tool.inputSchema && typeof tool.inputSchema === 'object' ? tool.inputSchema : {}),
  };
}
async function discoverMcp(connector, secret, signal) {
  const session = await openMcp(connector, secret, signal);
  try {
    const tools = [];
    let cursor;
    for (let page = 0; page < 5 && tools.length < MAX_TOOLS; page++) {
      const result = await session.request('tools/list', cursor ? { cursor } : {});
      for (const tool of result?.tools || []) { const mapped = mapMcpTool(tool); if (mapped) tools.push(mapped); }
      cursor = result?.nextCursor;
      if (!cursor) break;
    }
    return { tools: tools.slice(0, MAX_TOOLS), transport: session.transport, server: { name: clean(session.server.name, 80), version: clean(session.server.version, 40) } };
  } finally { session.close(); }
}
function mcpContent(result) {
  const parts = (Array.isArray(result?.content) ? result.content : []).map((c) => {
    if (c?.type === 'text') return String(c.text || '');
    if (c?.type === 'resource') return c.resource?.text ? String(c.resource.text) : `[resource ${c.resource?.uri || ''}]`;
    if (c?.type === 'resource_link') return `[link ${c.uri || ''}${c.name ? ` ${c.name}` : ''}]`;
    return `[${c?.type || 'content'}${c?.mimeType ? ` ${c.mimeType}` : ''}]`;
  });
  return parts.join('\n').slice(0, 40000);
}

// ---- REST APIs ----
function basePathOf(root) { return root.pathname.replace(/\/+$/, ''); }
function underBase(u, root) {
  const base = basePathOf(root);
  return u.origin === root.origin && (!base || u.pathname === base || u.pathname.startsWith(base + '/'));
}
function apiUrl(base, path = '', query) {
  const root = new URL(base), basePath = basePathOf(root);
  let p = String(path || '').trim();
  let target;
  if (/^[a-z][a-z0-9+.-]*:/i.test(p) || p.startsWith('//')) {
    try { target = new URL(p); } catch { throw badInput('path must be a path after the base URL, such as /v1/items.'); }
  } else {
    p = '/' + p.replace(/^\/+/, '');
    // A path that already starts with the base path is not repeated.
    if (basePath && (p === basePath || p.startsWith(basePath + '/') || p.startsWith(basePath + '?'))) p = p.slice(basePath.length) || '/';
    target = new URL(basePath + p, root.origin);
    for (const [k, v] of root.searchParams) if (!target.searchParams.has(k)) target.searchParams.set(k, v);
  }
  if (!underBase(target, root)) throw badInput(`This connector only reaches ${root.origin}${basePath}/…`);
  for (const [k, v] of Object.entries(query && typeof query === 'object' ? query : {})) {
    if (v == null) continue;
    if (Array.isArray(v)) { target.searchParams.delete(k); for (const item of v) target.searchParams.append(k, String(item)); }
    else target.searchParams.set(k, typeof v === 'object' ? JSON.stringify(v) : String(v));
  }
  return target.href;
}
function requestHeaders(input) {
  const out = {};
  for (const [name, value] of Object.entries(input && typeof input === 'object' ? input : {}).slice(0, 12)) {
    if (!/^[A-Za-z0-9-]{1,60}$/.test(name) || RESERVED_HEADERS.test(name)) throw badInput(`The ${name} header cannot be set; the saved credential is added for you.`);
    out[name] = String(value ?? '').slice(0, 500);
  }
  return out;
}
async function callApi(connector, secret, args, signal) {
  const method = String(args.method || 'GET').toUpperCase();
  if (!API_METHODS.some((m) => m.slug === method)) throw badInput('method must be GET, POST, PUT, PATCH or DELETE.');
  const headers = { Accept: 'application/json, text/plain;q=0.9, */*;q=0.5', ...requestHeaders(args.headers) };
  // Credential headers are set after the agent's own, so they always win.
  for (const name of Object.keys(headers)) if (connector.config?.auth?.type === 'header' && name.toLowerCase() === String(connector.config.auth.header).toLowerCase()) delete headers[name];
  const auth = authorize(apiUrl(connector.url, args.path, args.query), headers, connector.config?.auth, secret);
  let body;
  if (args.body != null && !['GET', 'DELETE'].includes(method)) {
    body = typeof args.body === 'string' ? args.body : JSON.stringify(args.body);
    if (body.length > 200000) throw badInput('The request body is too large (200 KB max).');
    if (!Object.keys(headers).some((h) => h.toLowerCase() === 'content-type')) headers['Content-Type'] = typeof args.body === 'string' ? 'text/plain; charset=utf-8' : 'application/json';
  }
  const res = await send(auth.url, { method, headers, body }, { signal, authHeaders: auth.authHeaders });
  const { text, truncated } = await readText(res);
  const type = String(res.headers.get('content-type') || '');
  let data;
  if (/json/.test(type) || /^\s*[[{]/.test(text)) { try { data = JSON.parse(text); } catch {} }
  const out = { status: res.status, ok: res.ok, ...(data !== undefined ? { data } : { text: text.slice(0, 30000) }), ...(truncated ? { truncated: true } : {}) };
  if (res.status === 401 || res.status === 403) out.note = 'The service refused the saved credential. Tell the owner they can update it under Connectors.';
  return out;
}

// ---- owner's connectors ----
function permissionsOf(c) {
  const off = new Set(c.disabled || []);
  if (c.kind === 'api') return API_METHODS.map((m) => ({ ...m, enabled: !off.has(m.slug) }));
  return (c.tools || []).map((t) => ({ slug: t.name, name: t.title || humanize(t.name), description: t.description || t.name, kind: t.kind, enabled: !off.has(t.name) }));
}
function ownerView(c) {
  const auth = c.config?.auth || { type: 'none' };
  return {
    id: c.id, kind: c.kind, slug: c.slug, name: c.name, url: c.url, host: hostOf(c.url), description: c.description,
    docsUrl: c.config?.docsUrl || '', testPath: c.config?.testPath || '', transport: c.config?.transport || '', server: c.config?.server || null,
    auth: { type: auth.type, ...(auth.header ? { header: auth.header } : {}), ...(auth.param ? { param: auth.param } : {}), ...(auth.username ? { username: auth.username } : {}) },
    secretId: c.secretId, status: c.status, lastError: c.lastError, checkedAt: c.checkedAt, at: c.at,
    permissions: permissionsOf(c),
  };
}
async function secretFor(userId, c) {
  if (!c.secretId) {
    if ((c.config?.auth?.type || 'none') !== 'none') throw Object.assign(new Error(`The saved credential for ${c.name} was deleted. Add it again under Connectors.`), { code: 'AUTH_FAILED' });
    return '';
  }
  const value = await store.revealSecret(userId, c.secretId);
  if (!value) throw Object.assign(new Error(`The saved credential for ${c.name} could not be read. Add it again under Connectors.`), { code: 'AUTH_FAILED' });
  return value;
}
// Checks a connector works with its credential: MCP servers list their tools; an API
// with a test path answers a GET there.
async function check(c, secret, signal) {
  try {
    if (c.kind === 'mcp') {
      const found = await discoverMcp(c, secret, signal);
      if (!found.tools.length) throw Object.assign(new Error('The MCP server answered but offers no tools.'), { code: 'CHECK_FAILED' });
      return { tools: found.tools, config: { ...c.config, transport: found.transport, server: found.server } };
    }
    if (c.config?.testPath) {
      const out = await callApi(c, secret, { method: 'GET', path: c.config.testPath }, signal);
      if (!out.ok) throw Object.assign(new Error(`The test request to ${c.config.testPath} answered HTTP ${out.status}.${out.status === 401 || out.status === 403 ? ' The key was refused.' : ''}`), { code: out.status === 401 || out.status === 403 ? 'AUTH_FAILED' : 'CHECK_FAILED' });
    }
    return { tools: [], config: c.config };
  } catch (error) {
    const out = reachError(error, c.url);
    out.message = String(scrub(out.message, secret, c.config?.auth));
    throw out;
  }
}
async function list(userId) {
  return (await store.listCustomConnectors(userId)).map(ownerView);
}
async function find(userId, ref) {
  const key = String(ref || '').trim().toLowerCase();
  if (!key) throw badInput('connector is required: the id composio_apps lists under custom.');
  const all = await store.listCustomConnectors(userId);
  const c = all.find((x) => x.id === ref || x.slug === key) || all.find((x) => x.name.toLowerCase() === key) || all.find((x) => x.slug.startsWith(key) || x.name.toLowerCase().startsWith(key));
  if (!c) throw badInput(`No connector named ${ref}. composio_apps lists the owner's connectors under custom.`);
  return c;
}
async function create(userId, input, { signal } = {}) {
  const v = cleanInput(input);
  const existing = await store.listCustomConnectors(userId);
  // The same address again (the agent set it up twice, or a key was refused) updates that
  // connector instead of adding a second one.
  const same = existing.find((c) => c.url === v.url);
  if (same) {
    if (v.secret) return replaceSecret(userId, same.id, v.secret, { signal });
    const connector = await refresh(userId, same.id, { signal });
    if (connector.status === 'error') throw Object.assign(new Error(connector.lastError || 'The connection check failed.'), { code: 'CHECK_FAILED' });
    return { connector, secret: null };
  }
  if (existing.length >= 30) throw badInput('You can add up to 30 of your own connectors.');
  const draft = { kind: v.kind, slug: slugFor(v.name, new Set(existing.map((c) => c.slug))), name: v.name, url: v.url, description: v.description,
    config: { auth: v.auth, ...(v.docsUrl ? { docsUrl: v.docsUrl } : {}), ...(v.testPath ? { testPath: v.testPath } : {}) }, disabled: [] };
  // Nothing is saved unless it works: a wrong URL or key is reported at once.
  const checked = await check(draft, v.secret, timeoutSignal(25000, signal));
  let secret = null;
  if (v.secret) secret = await store.addSecret(userId, `${v.name} ${v.kind === 'mcp' ? 'MCP token' : 'API key'}`, v.secret);
  try {
    const saved = await store.addCustomConnector(userId, { ...draft, config: checked.config, tools: checked.tools, secretId: secret?.id || null, status: 'connected', lastError: '', checkedAt: v.kind === 'mcp' || v.testPath ? Date.now() : null });
    return { connector: ownerView(saved), secret };
  } catch (error) {
    if (secret) await store.delSecret(userId, secret.id).catch(() => {});
    throw error;
  }
}
async function refresh(userId, id, { signal } = {}) {
  const c = await find(userId, id);
  try {
    const checked = await check(c, await secretFor(userId, c), timeoutSignal(25000, signal));
    const names = new Set(checked.tools.map((t) => t.name));
    const disabled = c.kind === 'mcp' ? c.disabled.filter((name) => names.has(name)) : c.disabled;
    return ownerView(await store.updateCustomConnector(userId, c.id, { tools: c.kind === 'mcp' ? checked.tools : c.tools, config: checked.config, disabled, status: 'connected', lastError: '', checkedAt: Date.now() }));
  } catch (error) {
    if (error.code === 'BAD_INPUT' || signal?.aborted) throw error;
    return ownerView(await store.updateCustomConnector(userId, c.id, { status: 'error', lastError: clean(error.message, 300), checkedAt: Date.now() }));
  }
}
// A new key replaces the old one in the vault once it works.
async function replaceSecret(userId, id, value, { signal } = {}) {
  const c = await find(userId, id);
  const secretValue = String(value || '').trim();
  if (!secretValue) throw badInput('Paste the new key or token.');
  if (secretValue.length > 4000) throw badInput('That key is too long to store (4,000 characters max).');
  if ((c.config?.auth?.type || 'none') === 'none') throw badInput('This connector uses no authentication.');
  const checked = await check(c, secretValue, timeoutSignal(25000, signal));
  const secret = await store.addSecret(userId, `${c.name} ${c.kind === 'mcp' ? 'MCP token' : 'API key'}`, secretValue);
  let saved;
  try {
    const names = new Set(checked.tools.map((t) => t.name));
    saved = await store.updateCustomConnector(userId, c.id, { secretId: secret.id, tools: c.kind === 'mcp' ? checked.tools : c.tools, config: checked.config, disabled: c.kind === 'mcp' ? c.disabled.filter((n) => names.has(n)) : c.disabled, status: 'connected', lastError: '', checkedAt: Date.now() });
  } catch (error) { await store.delSecret(userId, secret.id).catch(() => {}); throw error; }
  if (c.secretId) await store.delSecret(userId, c.secretId).catch(() => {});
  return { connector: ownerView(saved), secret };
}
async function setPermissions(userId, id, disabled) {
  const c = await find(userId, id);
  const known = new Set(permissionsOf(c).map((p) => p.slug));
  const next = [...new Set((Array.isArray(disabled) ? disabled : []).map(String).filter((slug) => known.has(slug)))];
  return ownerView(await store.updateCustomConnector(userId, c.id, { disabled: next }));
}
async function remove(userId, id) {
  const c = await find(userId, id);
  await store.deleteCustomConnector(userId, c.id);
  if (c.secretId) await store.delSecret(userId, c.secretId).catch(() => {});
  return { id: c.id };
}

// ---- the agent's view ----
// The connector a setup card added, found by its address.
async function findSetup(userId, args) {
  const { url } = setupArgs(args);
  return (await store.listCustomConnectors(userId)).find((c) => c.url === url) || null;
}
async function setupResult(userId, args) {
  const c = await findSetup(userId, args);
  if (!c) throw badInput(`${clean(args.name, 60) || 'The connector'} was not added. Ask the owner before trying again.`);
  const enabled = permissionsOf(c).filter((p) => p.enabled).map((p) => p.slug);
  return { added: true, connector: c.slug, name: c.name, kind: c.kind === 'mcp' ? 'MCP server' : 'API', status: c.status,
    ...(c.kind === 'mcp' ? { tools: enabled.slice(0, 40) } : { methods: enabled }),
    note: 'Connected. See what it can do with connector_tools and use it with connector_call.' };
}
async function forAgent(userId) {
  return (await store.listCustomConnectors(userId)).map((c) => ({
    connector: c.slug, name: c.name, kind: c.kind === 'mcp' ? 'MCP server' : 'API', host: hostOf(c.url),
    ...(c.description ? { about: c.description.slice(0, 240) } : {}),
    ...(c.status === 'error' ? { problem: c.lastError || 'The last check failed.' } : {}),
  }));
}
async function describe(userId, ref, query = '') {
  const c = await find(userId, ref);
  const perms = permissionsOf(c).filter((p) => p.enabled);
  if (c.kind === 'api') {
    const root = new URL(c.url);
    return {
      connector: c.slug, name: c.name, kind: 'API', baseUrl: `${root.origin}${basePathOf(root)}`,
      methods: perms.map((p) => p.slug), ...(c.description ? { about: c.description } : {}), ...(c.config?.docsUrl ? { docs: c.config.docsUrl } : {}),
      note: `Call connector_call with method and a path after the base URL. The credential is added for you.${c.config?.docsUrl ? ' Read the docs link with web_search for endpoints you do not know.' : ''} Methods not listed are turned off by the owner.`,
    };
  }
  const words = String(query || '').toLowerCase().split(/[^a-z0-9]+/).filter((w) => w.length > 2);
  const score = (t) => words.reduce((n, w) => n + (t.name.toLowerCase().includes(w) ? 3 : `${t.title} ${t.description}`.toLowerCase().includes(w) ? 1 : 0), 0);
  const enabled = new Set(perms.map((p) => p.slug));
  const tools = c.tools.filter((t) => enabled.has(t.name)).map((t, i) => [score(t), i, t]).sort((a, b) => b[0] - a[0] || a[1] - b[1]).map(([, , t]) => t);
  return {
    connector: c.slug, name: c.name, kind: 'MCP server', ...(c.description ? { about: c.description } : {}),
    tools: tools.slice(0, 40).map((t, i) => ({ name: t.name, kind: t.kind, description: t.description.split(/(?<=\.)\s/)[0].slice(0, 200), ...(i < 6 || words.length && score(t) > 0 && i < 12 ? { arguments: t.args } : {}) })),
    ...(tools.length > 40 ? { more: `${tools.length - 40} more tools; pass query to rank them.` } : {}),
    note: 'Call connector_call with tool and arguments. Tools not listed are turned off by the owner.',
  };
}
// What a call does, for the approval policy: 'read' or 'write'.
async function callKind(userId, args = {}) {
  const c = await find(userId, args.connector);
  if (c.kind === 'api') return API_METHODS.find((m) => m.slug === String(args.method || 'GET').toUpperCase())?.kind || 'write';
  return c.tools.find((t) => t.name === String(args.tool || ''))?.kind || 'write';
}
async function approvalDetail(userId, args = {}) {
  let c = null;
  try { c = await find(userId, args.connector); } catch {}
  const name = c ? c.name : clean(args.connector, 60) || 'your connector';
  if (!c || c.kind === 'mcp') {
    const tool = c?.tools.find((t) => t.name === args.tool);
    const input = args.arguments && typeof args.arguments === 'object' ? args.arguments : {};
    return JSON.stringify({ connector: c?.slug || args.connector, appName: name, action: tool?.title || humanize(args.tool) || 'Use a tool',
      fields: Object.entries(input).filter(([, value]) => value != null && value !== '').slice(0, 10).map(([k, value]) => ({ k: humanize(k), v: String(typeof value === 'object' ? JSON.stringify(value) : value).slice(0, 600) })),
      summary: `${humanize(args.tool) || 'Use a tool'} in ${name}` });
  }
  const method = String(args.method || 'GET').toUpperCase();
  let where = '';
  try { const u = new URL(apiUrl(c.url, args.path, args.query)); where = u.pathname + u.search; } catch { where = String(args.path || '/'); }
  const fields = [{ k: 'Request', v: `${method} ${where}`.slice(0, 600) }];
  if (args.body != null && !['GET', 'DELETE'].includes(method)) fields.push({ k: 'Body', v: (typeof args.body === 'string' ? args.body : JSON.stringify(args.body)).slice(0, 600) });
  const verb = { GET: 'Read from', POST: 'Send to', PUT: 'Replace in', PATCH: 'Update in', DELETE: 'Delete in' }[method] || 'Use';
  return JSON.stringify({ connector: c.slug, appName: name, action: `${verb} API`, fields, summary: `${method} ${where} on ${name}` });
}
async function call(userId, args = {}, { signal } = {}) {
  const c = await find(userId, args.connector);
  const perms = permissionsOf(c);
  const secret = await secretFor(userId, c);
  const sig = timeoutSignal(c.kind === 'mcp' ? 60000 : 30000, signal);
  let result, label;
  try {
    if (c.kind === 'mcp') {
      const name = String(args.tool || '').trim();
      if (!name) throw badInput('tool is required: a tool name from connector_tools.');
      const perm = perms.find((p) => p.slug === name);
      if (!perm) throw badInput(`${c.name} has no tool ${name}. Use connector_tools to see its tools.`);
      if (!perm.enabled) throw Object.assign(new Error(`The owner turned off ${perm.name} for ${c.name}.`), { code: 'PERMISSION_OFF' });
      const argsIn = args.arguments && typeof args.arguments === 'object' ? args.arguments : (args.args && typeof args.args === 'object' ? args.args : {});
      const session = await openMcp(c, secret, sig);
      let out;
      try { out = await session.request('tools/call', { name, arguments: argsIn }); } finally { session.close(); }
      const text = mcpContent(out);
      if (out?.isError) throw Object.assign(new Error((text || 'The tool reported an error.').slice(0, 600)), { code: 'MCP_ERROR' });
      result = { ...(out?.structuredContent ? { data: out.structuredContent } : {}), ...(text ? { text } : {}) };
      label = `${c.slug} ${name}`;
    } else {
      const method = String(args.method || 'GET').toUpperCase();
      const perm = perms.find((p) => p.slug === method);
      if (perm && !perm.enabled) throw Object.assign(new Error(`The owner turned off ${method} requests for ${c.name}.`), { code: 'PERMISSION_OFF' });
      result = await callApi(c, secret, args, sig);
      if (result.status === 401 || result.status === 403) throw Object.assign(new Error(result.note), { code: 'AUTH_FAILED', result });
      label = `${c.slug} ${method} ${result.status}`;
    }
  } catch (caught) {
    const error = reachError(caught, c.url);
    if (error.code === 'AUTH_FAILED' && c.status !== 'error') await store.updateCustomConnector(userId, c.id, { status: 'error', lastError: clean(error.message, 300), checkedAt: Date.now() }).catch(() => {});
    if (error.result) return { label: `${c.slug} refused`, result: compactResult(scrub(error.result, secret, c.config?.auth)) };
    error.message = String(scrub(error.message, secret, c.config?.auth));
    throw error;
  }
  if (c.status === 'error' || !c.checkedAt) await store.updateCustomConnector(userId, c.id, { status: 'connected', lastError: '', checkedAt: Date.now() }).catch(() => {});
  return { label, result: compactResult(scrub(result, secret, c.config?.auth)) };
}

module.exports = {
  API_METHODS, cleanInput, apiUrl, mcpToolKind, sseEvents,
  setupArgs, setupCard, setupDetail, findSetup, setupResult,
  list, create, refresh, replaceSecret, setPermissions, remove,
  forAgent, describe, callKind, approvalDetail, call, useTransport,
};
