/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AppRouteImport } from './routes/app'
import { Route as AppReturnRouteImport } from './routes/app-return'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PromoRouteImport } from './routes/promo'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as Research100mRouteImport } from './routes/research-100m'
import { Route as ResearchArche10RouteImport } from './routes/research-arche-1-0'
import { Route as ResearchStlmSlaRouteImport } from './routes/research-stlm-sla'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as SupportRouteImport } from './routes/support'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as WithdrawalRouteImport } from './routes/withdrawal'
import { Route as ApiSplatRouteImport } from './routes/api/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppReturnRoute = AppReturnRouteImport.update({
  id: '/app-return',
  path: '/app-return',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PromoRoute = PromoRouteImport.update({
  id: '/promo',
  path: '/promo',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const Research100mRoute = Research100mRouteImport.update({
  id: '/research-100m',
  path: '/research-100m',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchArche10Route = ResearchArche10RouteImport.update({
  id: '/research-arche-1-0',
  path: '/research-arche-1-0',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchStlmSlaRoute = ResearchStlmSlaRouteImport.update({
  id: '/research-stlm-sla',
  path: '/research-stlm-sla',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const WithdrawalRoute = WithdrawalRouteImport.update({
  id: '/withdrawal',
  path: '/withdrawal',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/app': typeof AppRoute
  '/app-return': typeof AppReturnRoute
  '/cookies': typeof CookiesRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/promo': typeof PromoRoute
  '/research': typeof ResearchRoute
  '/research-100m': typeof Research100mRoute
  '/research-arche-1-0': typeof ResearchArche10Route
  '/research-stlm-sla': typeof ResearchStlmSlaRoute
  '/security': typeof SecurityRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/withdrawal': typeof WithdrawalRoute
  '/api/$': typeof ApiSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/app': typeof AppRoute
  '/app-return': typeof AppReturnRoute
  '/cookies': typeof CookiesRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/promo': typeof PromoRoute
  '/research': typeof ResearchRoute
  '/research-100m': typeof Research100mRoute
  '/research-arche-1-0': typeof ResearchArche10Route
  '/research-stlm-sla': typeof ResearchStlmSlaRoute
  '/security': typeof SecurityRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/withdrawal': typeof WithdrawalRoute
  '/api/$': typeof ApiSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/app': typeof AppRoute
  '/app-return': typeof AppReturnRoute
  '/cookies': typeof CookiesRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/promo': typeof PromoRoute
  '/research': typeof ResearchRoute
  '/research-100m': typeof Research100mRoute
  '/research-arche-1-0': typeof ResearchArche10Route
  '/research-stlm-sla': typeof ResearchStlmSlaRoute
  '/security': typeof SecurityRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/withdrawal': typeof WithdrawalRoute
  '/api/$': typeof ApiSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/app'
    | '/app-return'
    | '/cookies'
    | '/pricing'
    | '/privacy'
    | '/promo'
    | '/research'
    | '/research-100m'
    | '/research-arche-1-0'
    | '/research-stlm-sla'
    | '/security'
    | '/support'
    | '/terms'
    | '/withdrawal'
    | '/api/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/app'
    | '/app-return'
    | '/cookies'
    | '/pricing'
    | '/privacy'
    | '/promo'
    | '/research'
    | '/research-100m'
    | '/research-arche-1-0'
    | '/research-stlm-sla'
    | '/security'
    | '/support'
    | '/terms'
    | '/withdrawal'
    | '/api/$'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/app'
    | '/app-return'
    | '/cookies'
    | '/pricing'
    | '/privacy'
    | '/promo'
    | '/research'
    | '/research-100m'
    | '/research-arche-1-0'
    | '/research-stlm-sla'
    | '/security'
    | '/support'
    | '/terms'
    | '/withdrawal'
    | '/api/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AppRoute: typeof AppRoute
  AppReturnRoute: typeof AppReturnRoute
  CookiesRoute: typeof CookiesRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  PromoRoute: typeof PromoRoute
  ResearchRoute: typeof ResearchRoute
  Research100mRoute: typeof Research100mRoute
  ResearchArche10Route: typeof ResearchArche10Route
  ResearchStlmSlaRoute: typeof ResearchStlmSlaRoute
  SecurityRoute: typeof SecurityRoute
  SupportRoute: typeof SupportRoute
  TermsRoute: typeof TermsRoute
  WithdrawalRoute: typeof WithdrawalRoute
  ApiSplatRoute: typeof ApiSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app-return': {
      id: '/app-return'
      path: '/app-return'
      fullPath: '/app-return'
      preLoaderRoute: typeof AppReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/promo': {
      id: '/promo'
      path: '/promo'
      fullPath: '/promo'
      preLoaderRoute: typeof PromoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research-100m': {
      id: '/research-100m'
      path: '/research-100m'
      fullPath: '/research-100m'
      preLoaderRoute: typeof Research100mRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research-arche-1-0': {
      id: '/research-arche-1-0'
      path: '/research-arche-1-0'
      fullPath: '/research-arche-1-0'
      preLoaderRoute: typeof ResearchArche10RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research-stlm-sla': {
      id: '/research-stlm-sla'
      path: '/research-stlm-sla'
      fullPath: '/research-stlm-sla'
      preLoaderRoute: typeof ResearchStlmSlaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/withdrawal': {
      id: '/withdrawal'
      path: '/withdrawal'
      fullPath: '/withdrawal'
      preLoaderRoute: typeof WithdrawalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AppRoute: AppRoute,
  AppReturnRoute: AppReturnRoute,
  CookiesRoute: CookiesRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  PromoRoute: PromoRoute,
  ResearchRoute: ResearchRoute,
  Research100mRoute: Research100mRoute,
  ResearchArche10Route: ResearchArche10Route,
  ResearchStlmSlaRoute: ResearchStlmSlaRoute,
  SecurityRoute: SecurityRoute,
  SupportRoute: SupportRoute,
  TermsRoute: TermsRoute,
  WithdrawalRoute: WithdrawalRoute,
  ApiSplatRoute: ApiSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
